### PR TITLE
remove "finish" event domain.dispose() codes.

### PR DESCRIPTION
**Pull request by fengmk2**
No need to call dispose() on 'finish' event.

### CODE REVIEW

**Comment by fengmk2** [comment]
It will let `connect.static` broken.

**Comment by baryshev** [comment]
I can't reproduce this bug on a real world example. Simple app with connect-static middleware and the same behaviour works fine.

**Comment by alaendle** [comment]
Don't know if this is the same problem. But I had the problem that in my case connect only responded to the first request - the second request hangs. After commenting out the dispose of the domain like requested in this issue thinks started to work as expected. Unfortunately I couldn't reproduce the problem on a small example - only my production app (which uses https://github.com/flatiron/resourceful and a MongoDb) the problem occurred.

So I wonder if I now build in something like a resource leak because I did no longer dispose the domain. Or is disposal unnecessary here?

**Comment by rprieto** [comment]
We also have problems with that line. Everything works locally, but every single requests hangs when deployed to Heroku behind SSL. This our (very basic) middleware redirect.

```
function sslMiddleware(req, res, next) {
    if (req.headers['x-forwarded-proto'] != 'https') {
        res.redirect('https://' + req.headers["host"] + req.url);
    } else {
        next();
    }
}
```

If I remove `res.on('finish', function () { reqDomain.dispose(); });` from `connect-domain`, everything works fine again.

**Pull request closed without merging**
